// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfo-FOR4F42GETfyBbzQ0sFR9AdN1_CN4',
    appId: '1:208362279267:android:331276d7fbd31cdb44c356',
    messagingSenderId: '208362279267',
    projectId: 'demoapp-44254',
    databaseURL: 'https://demoapp-44254.firebaseio.com',
    storageBucket: 'demoapp-44254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHAS9lAbNerbHvIH38qItxpjDeMCVbY4w',
    appId: '1:208362279267:ios:a6d214a0376b35c244c356',
    messagingSenderId: '208362279267',
    projectId: 'demoapp-44254',
    databaseURL: 'https://demoapp-44254.firebaseio.com',
    storageBucket: 'demoapp-44254.appspot.com',
    androidClientId: '208362279267-gq97nasq05ldjmnd2do4lr37tk8aie6l.apps.googleusercontent.com',
    iosClientId: '208362279267-9clgu219dlcokrvecl4h9pr097og7enh.apps.googleusercontent.com',
    iosBundleId: 'com.gplus.app.gplusapp',
  );
}
